repo: 'this-site-aint-no-sloth'
canvasCourse: 'web-dev-3'

inherit:
  - naming-restrict-live
  - git-2
  - html
  - css

html:
  - path: 'index.html'
    has:
      - 'main'
      - 'img'
      - 'h1'
      - 'figure figcaption'
    hasNot:
      - ['link[href*="grid"]', 'The `grid.css` file should not be included because it’s not used in the code']
    search:
      - 'This site ain’t no sloth'
      - 'The Mighty Sloth'
      - 'Megalonychidae'
      - 'Pilosa'

css:
  - path: 'css/main.css'
    has:
      - ['html']
    search:
      - 'Verdana'
      - 'Georgia'
      - '48px'
      - 'url\('
      - 'linear-gradient'
      - '#bea586'
      - 'rgba\(28\, 14\, 0'
  - path: 'css/modules.css'
    maxLines: 500
  - path: 'css/type.css'

files:
  - directory: 'images'
    maxSize: 300
    maxWidth: 1500
    maxHeight: 1100
    smushed: true
  - path: 'css/modules.css'
    maxSize: 7

performance:
  - path: 'index.html'

screenshots:
  - path: 'index.html'
    sizes:
      320: 18
      400: 18
      608: 18
      960: 17
      1440: 17
